<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { Delete, Plus } from '@lucide/vue';
import { ElMessage } from 'element-plus';
import { errorMessage } from '@shared/utils/errors';
import { runDatabaseObjectAction } from '../api/databaseManagement';

export type DatabaseObjectEditorContext = {
  assetId: number;
  database: string;
  schema: string;
  dbType: string;
  mode: 'create' | 'edit' | 'rename';
  objectType: 'table' | 'view' | 'function' | 'procedure';
  name: string;
  definition?: string;
  signature?: string;
};

const props = defineProps<{ modelValue: boolean; context: DatabaseObjectEditorContext | null }>();
const emit = defineEmits<{ 'update:modelValue': [value: boolean]; saved: [] }>();
const name = ref('');
const newName = ref('');
const definition = ref('');
const saving = ref(false);
const columns = ref([{ name: 'id', type: 'INTEGER', nullable: false, primary: true, autoIncrement: true, defaultValue: '' }]);

watch(() => [props.modelValue, props.context] as const, () => {
  if (!props.modelValue || !props.context) return;
  name.value = props.context.name;
  newName.value = props.context.name;
  definition.value = props.context.definition || starterDefinition(props.context);
  columns.value = [{ name: 'id', type: props.context.dbType === 'clickhouse' ? 'Int64' : 'INTEGER', nullable: false, primary: true, autoIncrement: props.context.dbType !== 'clickhouse', defaultValue: '' }];
}, { immediate: true });

function quote(value: string, dbType = props.context?.dbType || '') {
  if (['mysql', 'mariadb', 'clickhouse'].includes(dbType)) return `\`${value.replace(/`/g, '``')}\``;
  if (dbType === 'sqlserver') return `[${value.replace(/]/g, ']]')}]`;
  return `"${value.replace(/"/g, '""')}"`;
}

function starterDefinition(context: DatabaseObjectEditorContext) {
  const target = context.schema ? `${quote(context.schema, context.dbType)}.${quote(context.name || 'new_object', context.dbType)}` : quote(context.name || 'new_object', context.dbType);
  if (context.objectType === 'view') return 'SELECT *\nFROM ';
  if (['postgresql', 'kingbase'].includes(context.dbType)) {
    if (context.objectType === 'function') return `CREATE FUNCTION ${target}()\nRETURNS INTEGER LANGUAGE sql AS $$ SELECT 0 $$`;
    if (context.objectType === 'procedure') return `CREATE PROCEDURE ${target}()\nLANGUAGE plpgsql AS $$ BEGIN NULL; END $$`;
  }
  if (context.dbType === 'sqlserver') {
    if (context.objectType === 'function') return `CREATE FUNCTION ${target}()\nRETURNS INT AS BEGIN RETURN 0; END`;
    if (context.objectType === 'procedure') return `CREATE PROCEDURE ${target}\nAS BEGIN SELECT 1; END`;
  }
  if (['oracle', 'dameng'].includes(context.dbType)) {
    if (context.objectType === 'function') return `CREATE FUNCTION ${target} RETURN INTEGER IS\nBEGIN RETURN 0; END;`;
    if (context.objectType === 'procedure') return `CREATE PROCEDURE ${target} AS\nBEGIN NULL; END;`;
  }
  if (context.objectType === 'function') return `CREATE FUNCTION ${target}()\nRETURNS INTEGER\nBEGIN\n  RETURN 0;\nEND`;
  if (context.objectType === 'procedure') return `CREATE PROCEDURE ${target}()\nBEGIN\n  SELECT 1;\nEND`;
  return '';
}

const tableDefinition = computed(() => {
  if (!props.context || props.context.objectType !== 'table') return definition.value;
  const table = props.context.schema ? `${quote(props.context.schema)}.${quote(name.value)}` : quote(name.value);
  const fields = columns.value.filter(item => item.name.trim() && item.type.trim()).map(item => {
    const kind = props.context!.dbType;
    let text = `${quote(item.name.trim())} ${item.type.trim()}`;
    if (kind === 'sqlite' && item.autoIncrement) return `${quote(item.name.trim())} INTEGER PRIMARY KEY AUTOINCREMENT`;
    if (item.autoIncrement && ['postgresql', 'kingbase', 'oracle', 'dameng'].includes(kind)) text += ' GENERATED BY DEFAULT AS IDENTITY';
    if (item.autoIncrement && kind === 'sqlserver') text += ' IDENTITY(1,1)';
    if (!item.nullable) text += ' NOT NULL';
    if (item.autoIncrement && ['mysql', 'mariadb'].includes(kind)) text += ' AUTO_INCREMENT';
    if (item.defaultValue.trim()) text += ` DEFAULT ${item.defaultValue.trim()}`;
    return text;
  });
  const primary = columns.value.filter(item => item.primary);
  if (primary.length && !(props.context.dbType === 'sqlite' && columns.value.some(item => item.autoIncrement))) fields.push(`PRIMARY KEY (${primary.map(item => quote(item.name.trim())).join(', ')})`);
  const suffix = props.context.dbType === 'clickhouse' ? ` ENGINE = MergeTree ORDER BY ${primary.length ? `(${primary.map(item => quote(item.name.trim())).join(', ')})` : 'tuple()'}` : '';
  return `CREATE TABLE ${table} (\n  ${fields.join(',\n  ')}\n)${suffix}`;
});

const title = computed(() => {
  if (!props.context) return '数据库对象';
  const labels = { table: '表', view: '视图', function: '函数', procedure: '存储过程' };
  return `${props.context.mode === 'create' ? '新建' : props.context.mode === 'rename' ? '重命名' : '编辑'}${labels[props.context.objectType]}`;
});

async function save() {
  const context = props.context;
  if (!context) return;
  if (context.objectType === 'table' && context.mode === 'create' && context.dbType === 'sqlite' && columns.value.some(item => item.autoIncrement) && (columns.value.filter(item => item.primary).length !== 1 || columns.value.some(item => item.autoIncrement && (!item.primary || item.type.toUpperCase() !== 'INTEGER')))) {
    ElMessage.error('SQLite 自增字段必须是唯一的 INTEGER 主键'); return;
  }
  if (context.mode === 'edit' && !window.confirm(`确定覆盖“${context.name}”的数据库定义吗？`)) return;
  saving.value = true;
  try {
    await runDatabaseObjectAction(context.assetId, {
      action: context.mode === 'rename' ? 'rename' : context.mode === 'edit' ? 'replace' : 'create',
      database: context.database, schema: context.schema, objectType: context.objectType,
      signature: context.signature,
      name: context.mode === 'create' ? name.value : context.name,
      newName: context.mode === 'rename' ? newName.value : undefined,
      definition: context.objectType === 'table' ? tableDefinition.value : definition.value,
    });
    emit('update:modelValue', false); emit('saved');
  } catch (error) { ElMessage.error(errorMessage(error)); }
  finally { saving.value = false; }
}
</script>

<template>
  <el-dialog :model-value="modelValue" :title="title" width="min(760px, 94vw)" :close-on-click-modal="false" @update:model-value="emit('update:modelValue', $event)">
    <el-form v-if="context" label-position="top">
      <el-form-item v-if="context.mode === 'create'" label="名称"><el-input v-model="name" /></el-form-item>
      <el-form-item v-else-if="context.mode === 'rename'" label="新名称"><el-input v-model="newName" /></el-form-item>
      <template v-else-if="context.objectType === 'table'" />
      <template v-if="context.objectType === 'table' && context.mode === 'create'">
        <div class="object-fields-head"><strong>字段</strong><el-button size="small" @click="columns.push({ name: '', type: 'VARCHAR(255)', nullable: true, primary: false, autoIncrement: false, defaultValue: '' })"><Plus :size="14" />添加字段</el-button></div>
        <div v-for="(column, index) in columns" :key="index" class="object-field-row">
          <el-input v-model="column.name" placeholder="字段名" /><el-input v-model="column.type" placeholder="类型" />
          <el-input v-model="column.defaultValue" placeholder="默认值" />
          <el-checkbox v-model="column.nullable">可空</el-checkbox><el-checkbox v-model="column.primary">主键</el-checkbox><el-checkbox v-model="column.autoIncrement">自增</el-checkbox>
          <el-button text type="danger" :disabled="columns.length === 1" @click="columns.splice(index, 1)"><Delete :size="14" /></el-button>
        </div>
        <el-form-item label="SQL 预览"><el-input :model-value="tableDefinition" type="textarea" :rows="7" readonly /></el-form-item>
      </template>
      <el-form-item v-else-if="context.mode !== 'rename'" label="SQL 定义"><el-input v-model="definition" type="textarea" :rows="14" /></el-form-item>
    </el-form>
    <template #footer><el-button @click="emit('update:modelValue', false)">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template>
  </el-dialog>
</template>

<style scoped>
.object-fields-head,.object-field-row{display:flex;align-items:center;gap:8px}.object-fields-head{justify-content:space-between;margin-bottom:8px}.object-field-row{margin-bottom:8px}.object-field-row>.el-input{flex:1}.object-field-row>.el-checkbox{margin-right:0;white-space:nowrap}@media(max-width:720px){.object-field-row{flex-wrap:wrap}.object-field-row>.el-input{flex:1 1 180px}}
</style>
