# Generated by Django 5.2.17 on 2026-10-01 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0004_saveddatabasequery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTransferTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('import', 'import'), ('export', 'export')], max_length=8)),
                ('scope', models.CharField(max_length=32)),
                ('format', models.CharField(blank=True, max_length=16)),
                ('database', models.CharField(blank=True, max_length=160)),
                ('schema', models.CharField(blank=True, max_length=160)),
                ('object_name', models.CharField(blank=True, max_length=256)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('conflict_policy', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('uploading', 'uploading'), ('inspecting', 'inspecting'), ('awaiting_confirmation', 'awaiting_confirmation'), ('queued', 'queued'), ('running', 'running'), ('cancel_requested', 'cancel_requested'), ('cancelled', 'cancelled'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('expired', 'expired')], db_index=True, default='queued', max_length=32)),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('processed_rows', models.BigIntegerField(default=0)),
                ('processed_bytes', models.BigIntegerField(default=0)),
                ('total_rows', models.BigIntegerField(blank=True, null=True)),
                ('total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('checkpoints', models.JSONField(blank=True, default=dict)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('input_path', models.CharField(blank=True, max_length=1024)),
                ('output_path', models.CharField(blank=True, max_length=1024)),
                ('error', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_tasks', to='database_management.databaseasset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_transfer_tasks', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='database_management.databasetransfertask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
