<script setup lang="ts">
import {
  Bell,
  Bookmark,
  Brush,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  Clipboard,
  Copy,
  Database,
  DatabaseBackup,
  DatabaseZap,
  CornerDownLeft,
  Cpu,
  Download,
  Edit3,
  Eye,
  EyeOff,
  File,
  FileCode2,
  Folder,
  FolderOpen,
  FolderPlus,
  Gauge,
  Globe2,
  HardDrive,
  Image,
  Info,
  History,
  KeyRound,
  Laptop,
  LayoutDashboard,
  Link,
  LockKeyhole,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Monitor,
  Moon,
  MoveRight,
  Network,
  Palette,
  Pin,
  PanelLeft,
  Plus,
  QrCode,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Rows3,
  ScanLine,
  Search,
  Scissors,
  Server,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  SquareTerminal,
  Sun,
  SunMoon,
  SwatchBook,
  Trash2,
  Upload,
  User,
  UserCog,
  Users,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from '@lucide/vue';
import { computed } from 'vue';

const props = withDefaults(defineProps<{ name: IconName; size?: number; strokeWidth?: number }>(), {
  size: 18,
  strokeWidth: 2,
});

const icons = {
  alert: CircleAlert,
  bell: Bell,
  bookmark: Bookmark,
  brush: Brush,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronsRight: ChevronsRight,
  circleCheck: CircleCheck,
  circleHelp: CircleHelp,
  circlePlus: CirclePlus,
  clipboard: Clipboard,
  copy: Copy,
  database: Database,
  databaseBackup: DatabaseBackup,
  databaseZap: DatabaseZap,
  cornerDownLeft: CornerDownLeft,
  cpu: Cpu,
  dashboard: LayoutDashboard,
  download: Download,
  edit: Edit3,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  fileCode: FileCode2,
  folder: Folder,
  folderOpen: FolderOpen,
  folderPlus: FolderPlus,
  gauge: Gauge,
  globe: Globe2,
  hardDrive: HardDrive,
  image: Image,
  info: Info,
  history: History,
  key: KeyRound,
  laptop: Laptop,
  link: Link,
  lock: LockKeyhole,
  logout: LogOut,
  maximize: Maximize2,
  menu: Menu,
  minimize: Minimize2,
  monitor: Monitor,
  moon: Moon,
  moveRight: MoveRight,
  network: Network,
  palette: Palette,
  pin: Pin,
  panelLeft: PanelLeft,
  plus: Plus,
  qr: QrCode,
  refresh: RefreshCw,
  reset: RotateCcw,
  rotate: RotateCw,
  rows: Rows3,
  scan: ScanLine,
  search: Search,
  scissors: Scissors,
  server: Server,
  settings: Settings,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sun: Sun,
  sunMoon: SunMoon,
  swatch: SwatchBook,
  terminal: SquareTerminal,
  trash: Trash2,
  upload: Upload,
  user: User,
  userCog: UserCog,
  users: Users,
  x: X,
  zap: Zap,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
};

export type IconName = keyof typeof icons;

const iconComponent = computed(() => icons[props.name]);
</script>

<template>
  <component
    :is="iconComponent"
    class="app-icon"
    :size="size"
    :stroke-width="strokeWidth"
    aria-hidden="true"
  />
</template>
